SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE SPIL_PRG_LI_CLM_MATURE_INVESTMENT
@pPOLICY_NUMBER nvarchar(25)

AS
BEGIN
DECLARE @pCONTRIBUTION_CLAIM numeric(18, 2), @pTOTAL_LOAN_REPAID numeric(18, 2), @pTOTAL_LOAN_GRANTED numeric(18, 2), @pLOAN_BALANCE numeric(18, 2)

	--SET NOCOUNT ON;
select @pCONTRIBUTION_CLAIM = (SELECT SUM(TBFN_TRANS_TOT_AMT) AS 'CONTRIBUTION AMT'      
FROM [ABS_LIFE].[dbo].[TBFN_ALLOC_DETAIL]
where (TBFN_TRANS_POLY_NO=@pPOLICY_NUMBER) and (TBFN_TRANS_TYPE='N') OR (TBFN_TRANS_TYPE='L') OR (TBFN_TRANS_TYPE='I'))


SELECT @pTOTAL_LOAN_GRANTED = (SELECT SUM(TBIL_LOAN_DISB_LOAN_AMT_LC) AS 'TOTAL LOAN GRANTED'      
  FROM [ABS_LIFE].[dbo].[TBIL_LOAN_DISBURSE]
  where (TBIL_LOAN_DISB_POLY_NO=@pPOLICY_NUMBER))
  
  
SELECT @pTOTAL_LOAN_REPAID = (SELECT SUM(TBIL_LOAN_REPAY_AMT_FC) AS TOT_LOAN_GRANTD      
  FROM [ABS_LIFE].[dbo].[TBIL_LOAN_REPAID]
  where (TBIL_LOAN_REPAY_POLY_NO=@pPOLICY_NUMBER))
  
  
  
END
GO
