USE [ABS_LIFE]
GO

/****** Object:  StoredProcedure [dbo].[SPIL_GET_ALL_ACTIVE_POLICY]    Script Date: 08/03/2015 13:54:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
ALTER PROCEDURE [dbo].[SPIL_GET_ALL_ACTIVE_POLICY]
@pPolicy_No nvarchar(50) =''
AS
BEGIN
	SELECT WK.TBIL_POLY_POLICY_NO AS POLICY_NO, WK.[TBIL_POLY_ASSRD_CD] AS ASSURED_CODE,
		  WV.TBIL_INSRD_SURNAME AS FULLNAME,
		   --(WV.TBIL_INSRD_SURNAME + ' ' + WV.TBIL_INSRD_FIRSTNAME AS FULLNAME,
		   WS.TBIL_POL_PRM_PRDCT_CD AS PRODUCT_CODE, 
		   CONVERT(VARCHAR(10),WS.TBIL_POL_PRM_FROM, 103) AS START_DT,
		   CONVERT(VARCHAR(10),WS.TBIL_POL_PRM_TO, 103) AS END_DT, 
		   WU.TBIL_PRDCT_DTL_DESC AS PRODUCT_NAME,
		   (SELECT 
			 CONVERT(VARCHAR(10),(DATEADD(month, (SUM(TBFN_TRANS_TOT_AMT)/WS.TBIL_POL_PRM_MTH_CONTRIB_FC), WS.TBIL_POL_PRM_FROM)), 103) AS [DD/MM/YYYY]
			FROM TBFN_ALLOC_DETAIL WHERE TBFN_TRANS_POLY_NO=WK.TBIL_POLY_POLICY_NO AND TBFN_TRANS_TYPE='N')  AS LAST_PREMIUM
		
	FROM TBIL_POLICY_DET AS WK 
	INNER JOIN tbil_ins_detail AS WV ON WK.TBIL_POLY_ASSRD_CD=WV.TBIL_INSRD_CODE
    INNER JOIN TBIL_POLICY_PREM_INFO AS WS ON WK.TBIL_POLY_POLICY_NO=WS.TBIL_POL_PRM_POLY_NO
	INNER JOIN TBIL_PRODUCT_DETL AS WU ON WS.TBIL_POL_PRM_PRDCT_CD=WU.TBIL_PRDCT_DTL_CODE
	WHERE TBIL_POLY_STATUS='A' and TBIL_POLY_POLICY_NO LIKE '%' + RTRIM(@pPolicy_No) + '%'
END


GO


