USE [ABS_LIFE]
GO

/****** Object:  StoredProcedure [dbo].[SPIL_GET_CLAIM_WAIVER_RPT]    Script Date: 07/30/2015 13:17:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[SPIL_GET_PAIDUP_POLICIES_RPT]
(@pSTART_DATE	DATETIME
	,@pEND_DATE DATETIME
)
AS
BEGIN
	
SELECT WK.[TBIL_POLY_ASSRD_CD], WK.TBIL_POLY_POLICY_NO, WK.TBIL_POLY_PAIDUP_DT, 
	  (WV.TBIL_INSRD_SURNAME + ' ' + WV.TBIL_INSRD_FIRSTNAME) AS FULLNAME,
	   WS.TBIL_POL_PRM_PRDCT_CD, WS.TBIL_POL_PRM_FROM,
	   WS.TBIL_POL_PRM_TO, WU.TBIL_PRDCT_DTL_DESC
FROM TBIL_POLICY_DET AS WK
	   INNER JOIN tbil_ins_detail AS WV ON WK.TBIL_POLY_ASSRD_CD=WV.TBIL_INSRD_CODE
	   INNER JOIN TBIL_POLICY_PREM_INFO AS WS ON WK.TBIL_POLY_POLICY_NO=WS.TBIL_POL_PRM_POLY_NO
	   INNER JOIN TBIL_PRODUCT_DETL AS WU ON WS.TBIL_POL_PRM_PRDCT_CD=WU.TBIL_PRDCT_DTL_CODE
	  
WHERE TBIL_POLY_STATUS ='P' AND TBIL_POLY_PAIDUP_DT >=@pSTART_DATE AND TBIL_POLY_PAIDUP_DT <=@pEND_DATE
	   ORDER BY TBIL_POLY_WAIVER_DT ASC
	
END

GO


